// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crldvpzzhourlxwvvfae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybGR2cHp6aG91cmx4d3Z2ZmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTA0NjUsImV4cCI6MjA2NTc2NjQ2NX0.83r_SFS-heOYfqZ-IAQ8SYvjgyb7kMfIuzLAenbRX3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);